name: flutter_grocery
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  provider: ^6.1.2
  http: ^0.13.6
  shared_preferences: ^2.2.3
  photo_view: ^0.15.0
  dio: ^5.4.3+1
  image_picker: ^1.1.0
  pin_code_fields: ^8.0.1
  google_maps_flutter_web: ^0.5.6+2
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.2.6
  firebase_core: 3.12.1
  firebase_messaging: 15.2.4
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.3
#  connectivity: ^3.0.6
  connectivity_plus: ^6.0.5
  carousel_slider: ^5.0.0
  fluro: ^2.0.5
  url_strategy: ^0.3.0
  universal_html: ^2.2.4
  flutter_widget_from_html_core: ^0.16.0
#  phone_number: ^2.1.0
  country_code_picker: ^3.3.0
  flutter_typeahead: ^5.2.0
  flutter_inappwebview: ^6.0.0
  cached_network_image: ^3.3.1
  audioplayers: ^6.0.0
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.1
  expandable_bottom_sheet: ^1.1.1+1
  dotted_border: ^2.1.0
  share_plus: ^10.1.4
  scroll_to_index: ^3.0.1
  simple_speed_dial: ^0.1.7
  sign_in_with_apple: ^6.1.0
  firebase_auth: 5.5.1
  flutter_svg: ^2.0.9
  flutter_xlider: ^3.5.0
  firebase_crashlytics: 4.3.4
  firebase_analytics: ^11.3.3
  aptabase_flutter: ^0.1.0
  phone_numbers_parser: ^9.0.3
  dropdown_button2: ^2.3.9
  app_links: ^6.3.1
  drift: ^2.19.0
  drift_flutter: ^0.2.4
  cached_network_image_platform_interface:
  just_the_tooltip: ^0.0.12
  fluttertoast: ^8.2.12
  # H5 JavaScript bridge support for Telebirr integration
  js: ^0.7.1
  # QR code generation for desktop fallback
  qr_flutter: ^4.1.0
  # Telebirr payment integration for Android native app
  telebirr_payment: ^0.1.6
  # RSA signature generation for C2B integration
  crypto: ^3.0.3
  collection: any
  google_maps_webservice: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.19.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700